name: Release Insiders

on:
  push:
    branches: [master]

permissions:
  contents: read

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      #   cache: 'npm'
      #
      # - name: Use cached node_modules
      #   id: cache
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: nodeModules-${{ hashFiles('**/package-lock.json') }}-${{ matrix.node-version }}
      #     restore-keys: |
      #       nodeModules-

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Tailwind CSS
        run: npm run swcify

      - name: Test
        run: npm test

      - name: Resolve version
        id: vars
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Version based on commit: 0.0.0-insiders.${{ env.SHA_SHORT }}'
        run: npm version 0.0.0-insiders.${{ env.SHA_SHORT }} --force --no-git-tag-version

      - name: Publish
        run: npm publish --tag insiders
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Trigger Tailwind Play update
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TAILWIND_PLAY_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'tailwindlabs',
              repo: 'play.tailwindcss.com',
              ref: 'master',
              workflow_id: 'upgrade-tailwindcss.yml',
              inputs: {
                insidersVersion: '0.0.0-insiders.${{ env.SHA_SHORT }}'
              }
            })
