[package]
description = "ICU MessageFormat Parser"
edition     = "2021"
license     = "MIT"
name        = "icu-messageformat-parser"
repository  = "https://github.com/formatjs/formatjs"
version     = "0.0.2"

[features]
utf16 = ["widestring"]

[dependencies]
langtag    = { workspace = true }
once_cell  = { workspace = true }
regex      = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
widestring = { workspace = true, optional = true }

[dev-dependencies]
serde_json      = { workspace = true }
similar-asserts = { workspace = true }
testing         = { workspace = true }
