[package]
authors = [
  "OJ Kwon <kwon.ohjoong@gmail.com>",
  "DongYoon Kang <kdy1997.dev@gmail.com>",
]
description = "ICU MessageFormat Parser"
edition = "2021"
license = "MIT"
name = "icu-messageformat-parser"
repository = "https://github.com/swc-project/plugins"
version = "1.0.0"

[features]
utf16 = ["widestring"]

[dependencies]
langtag    = { workspace = true }
once_cell  = { workspace = true }
regex      = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
widestring = { workspace = true, optional = true }

[dev-dependencies]
serde_json      = { workspace = true }
similar-asserts = { workspace = true }
testing         = { workspace = true }
