[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for tailwind"
edition = "2021"
license = "Apache-2.0"
name = "swc_tailwind"
repository = "https://github.com/swc-project/plugins.git"
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
swc_atoms = "0.4.24"
swc_core = {version = "0.40.46", features = [
  "common",
  "css_ast",
  "css_codegen",
  "css_parser",
  "css_visit",
  "ecma_visit",
]}
swc_timer = "0.17.13"

[dev-dependencies]
serde_json = "1"
testing = "0.31.13"
