[package]

description = "SWC plugin for https://www.npmjs.com/package/babel-plugin-remove-console"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_plugin_remove_console"
publish      = false
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.19.4"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
remove_console   = { path = "./transform" }
serde_json       = "1.0.117"
swc_common       = { version = "0.37.0", features = ["concurrent"] }
swc_core         = { version = "0.100.0", features = ["ecma_plugin_transform"] }
swc_ecma_ast     = "0.118.0"
swc_ecma_utils   = "0.134.0"
swc_ecma_visit   = "0.104.0"
swc_plugin_macro = "0.9.16"
tracing          = { version = "0.1.40", features = ["release_max_level_off"] }
