[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC plugin for https://www.npmjs.com/package/babel-plugin-remove-console"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_remove_console"
publish = false
version = "0.14.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
remove_console = { path = "./transform" }
serde_json = "1.0.79"
swc_common = { version = "0.33.12", features = ["concurrent"] }
swc_core = { version = "0.87.3", features = ["ecma_plugin_transform"] }
swc_ecma_ast = "0.110.15"
swc_ecma_utils = "0.125.0"
swc_ecma_visit = "0.96.15"
swc_plugin_macro = "0.9.15"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
