[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC plugin for https://www.npmjs.com/package/babel-plugin-react-remove-properties"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_react_remove_properties"
publish = false
version = "0.13.3"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
react_remove_properties = { path = "./transform" }
serde_json = "1.0.79"
swc_cached = "0.3.17"
swc_common = { version = "0.33.0", features = ["concurrent"] }
swc_core = { version = "0.86.1", features = ["ecma_plugin_transform"] }
swc_ecma_ast = "0.110.0"
swc_ecma_utils = "0.124.4"
swc_ecma_visit = "0.96.0"
swc_plugin_macro = "0.9.15"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
