[package]

description = "SWC plugin for https://www.npmjs.com/package/babel-plugin-react-remove-properties"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_plugin_react_remove_properties"
publish      = false
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.19.4"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
react_remove_properties = { path = "./transform" }
serde_json              = "1.0.117"
swc_cached              = "0.3.20"
swc_common              = { version = "0.36.0", features = ["concurrent"] }
swc_core                = { version = "0.99.2", features = ["ecma_plugin_transform"] }
swc_ecma_ast            = "0.117.0"
swc_ecma_utils          = "0.133.1"
swc_ecma_visit          = "0.103.1"
swc_plugin_macro        = "0.9.16"
tracing                 = { version = "0.1.40", features = ["release_max_level_off"] }
