[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for swc constify plugin"
edition = "2021"
license = "Apache-2.0"
name = "swc_constify"
repository = "https://github.com/swc-project/plugins.git"
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1.37" }
rustc-hash = "1.1.0"

swc_core = { features = [
    "common",
    "ecma_ast",
    "ecma_utils",
    "ecma_visit",
], version = "0.82.10" }


[dev-dependencies]
serde_json = "1"
swc_core = { features = [
    "testing_transform",
    "ecma_parser",
], version = "0.82.10" }
testing = "0.34.1"
