[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for swc constify plugin"
edition = "2021"
license = "Apache-2.0"
name = "swc_constify"
repository = "https://github.com/swc-project/plugins.git"
version = "0.18.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1.37" }
rustc-hash = "1.1.0"

swc_common = "0.33.0"
swc_ecma_ast = "0.110.0"
swc_ecma_utils = "0.124.4"
swc_ecma_visit = "0.96.0"
swc_atoms = "0.6.0"
once_cell = "1.18.0"


[dev-dependencies]
serde_json = "1"
swc_ecma_parser = "0.141.1"
swc_ecma_transforms_base = "0.134.4"
swc_ecma_transforms_testing = "0.137.4"
testing = "0.35.0"
