[package]
authors = [
  "OJ Kwon <kwon.ohjoong@gmail.com>",
  "DongYoon Kang <kdy1997.dev@gmail.com>",
]
description = "formatjs custom transform visitor for SWC"
edition.workspace = true
license.workspace = true
name = "swc-formatjs-visitor"
repository.workspace = true
version = "1.0.0"

[features]
custom_transform = []

[dependencies]
base64ct = { workspace = true, features = ["alloc"] }
icu-messageformat-parser = { version = "0.0.2", path = "../icu-messageformat-parser", features = [
  "utf16",
] }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
swc_core = { workspace = true, features = ["common", "ecma_visit", "ecma_ast"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
