[package]
description = "AST Transforms for styled-components, without dependency on plugin apis"
edition = "2018"
license = "Apache-2.0"
name = "styled_components"
version = "0.25.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
once_cell = "1.10.0"
regex = {version = "1.5.4", features = ["std", "perf"], default-features = false}
serde = {version = "1.0.130", features = ["derive"]}
swc_atoms = "0.2.11"
swc_common = { version = "0.17.19", features = ["concurrent"] }
swc_ecmascript = { version = "0.140.0", features = ["utils", "visit"] }
tracing = "0.1"

[dev-dependencies]
serde_json = "1"
swc_ecma_transforms_testing = "0.75.0"
swc_ecmascript = { version = "0.140.0", features = ["parser", "transforms"] }
testing = "0.19.1"
