[package]
description = "AST Transforms for styled-components, without dependency on plugin apis"
edition = "2018"
license = "Apache-2.0"
name = "styled_components"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = {version = "1.5.4", features = ["std", "perf"], default-features = false}
swc_atoms = "0.2.9"
swc_common = "0.14.2"
swc_ecmascript = {version = "0.82.0", features = ["utils", "visit"]}

[dev-dependencies]
swc_ecma_transforms_testing = "0.42.0"
testing = "0.15.1"
