[package]
description = "AST Transforms for styled-components, without dependency on plugin apis"
edition = "2018"
license = "Apache-2.0"
name = "styled_components"
version = "0.16.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
once_cell = "1.8.0"
regex = {version = "1.5.4", features = ["std", "perf"], default-features = false}
serde = {version = "1.0.130", features = ["derive"]}
swc_atoms = "0.2.9"
swc_common = {version = "0.17.5", features = ["concurrent"]}
swc_ecmascript = {version = "0.118.0", features = ["utils", "visit"]}
tracing = "0.1.29"

[dev-dependencies]
serde_json = "1.0.69"
swc_ecma_transforms_testing = "0.63.0"
swc_ecmascript = {version = "0.118.0", features = ["parser", "transforms"]}
testing = "0.18.0"
