[package]
description = "AST Transforms for styled-components, without dependency on plugin apis"
edition = "2018"
license = "Apache-2.0"
name = "styled_components"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_ecmascript = {version = "0.82.0", features = ["utils", "visit"]}
